Improve security on workflow ok-to-test
Do not rely on PR-defined input to push images to quay.io

The existing ok-to-test label protection aims to avoid running untrusted
code, however in the event that maintainers approve malicious code
unintentionally, there was a risk that the attacker leverages this
PR-defined input. PR data is now extracted from a safe source.

diff --git a/.github/workflows/push_image_pr.yml b/.github/workflows/push_image_pr.yml
--- a/.github/workflows/push_image_pr.yml
+++ b/.github/workflows/push_image_pr.yml
@@ -5,8 +5,14 @@ on:
     types:
       - completed
 
+permissions:
+  pull-requests: write
+
 env:
   WF_REGISTRY_USER: netobserv+github_ci
+  WF_REGISTRY: quay.io/netobserv
+  WF_IMAGE: network-observability-console-plugin
+  WF_IMAGE_SA: network-observability-standalone-frontend
 
 jobs:
   push-pr-image:
@@ -16,6 +22,21 @@ jobs:
     name: push PR image
     runs-on: ubuntu-latest
     steps:
+      - name: extract PR data
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          pr_json=$(gh api "repos/${{ github.repository }}/pulls?state=open&head=${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}")
+          len=$(echo ${pr_json} | jq '. | length')
+          if [[ "$len" != "1" ]]; then
+            echo "::error::Could not get a unique PR, aborting"
+            exit 1
+          fi
+          echo "pr_id=$(echo ${pr_json} | jq '.[0].number')" >> $GITHUB_ENV
+          head_sha=$(echo ${pr_json} | jq -r '.[0].head.sha')
+          echo "short_sha=$(echo ${head_sha::8})" >> $GITHUB_ENV
+          echo "main_image=${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE }}:${head_sha::8}" >> $GITHUB_ENV
+          echo "sa_image=${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE_SA }}:${head_sha::8}" >> $GITHUB_ENV
       - name: download artifact
         uses: actions/download-artifact@v8
         with:
@@ -26,6 +47,8 @@ jobs:
         run: |
           docker load --input ./image.tar
           docker load --input ./image-standalone.tar
+          docker image tag ${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE }}:tmp ${{ env.main_image }}
+          docker image tag ${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE }}:tmp ${{ env.sa_image }}
       - name: docker login to quay.io
         uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
         with:
@@ -34,32 +57,28 @@ jobs:
           registry: quay.io
       - name: push images
         run: |
-          DOCKER_BUILDKIT=1 docker push $(cat ./name)
-          DOCKER_BUILDKIT=1 docker push $(cat ./name-standalone)
+          DOCKER_BUILDKIT=1 docker push ${{ env.main_image }}
+          DOCKER_BUILDKIT=1 docker push ${{ env.sa_image }}
       - uses: actions/github-script@v9
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             var fs = require('fs');
-            var issueNumber = Number(fs.readFileSync('./pr-id'));
-            var shortSha = String(fs.readFileSync('./short-sha')).trim();
-            var mainImage = fs.readFileSync('./name');
-            var standaloneImage = fs.readFileSync('./name-standalone');
             github.rest.issues.createComment({
-              issue_number: issueNumber,
+              issue_number: ${{ env.pr_id }},
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: `New images:
             \`\`\`bash
-            ${mainImage}
-            ${standaloneImage}
+            ${{ env.main_image }}
+            ${{ env.sa_image }}
             \`\`\`
 
             They will expire in two weeks.
 
             To deploy this build, run from the operator repo, assuming the operator is running:
             \`\`\`bash
-            USER=netobserv VERSION=${shortSha} make set-plugin-image
+            USER=netobserv VERSION=${{ env.short_sha }} make set-plugin-image
             \`\`\`
             `
             })
